2024-02-06 03:59:39,529 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_assist_enabled] [2669] Telemetry sud optin query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089/services/properties/telemetry/general/sendSupportUsage: [Errno 111] Connection refused',)
2024-02-06 03:59:39,538 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_search_head] [2669] Search head query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089//services/server/roles: [Errno 111] Connection refused',)
2024-02-06 04:00:54,748 INFO [assist::uiassets_modular_input.py] [uiassets_modular_input] [_run] [3987] Supervisor update required, etag="8caf8e0826646505d41e4ce77ea9b72b", url=https://beam.scs.splunk.com/com.splunk.assist.ui/latest/com.splunk.assist.ui-assets.tgz
2024-02-06 04:00:54,953 INFO [assist::uiassets_modular_input.py] [download] [run] [3987] Download command started
2024-02-06 04:00:55,777 INFO [assist::uiassets_modular_input.py] [logging] [log_process_output] [3987] Download will extract, file=/opt/splunk/var/splunk_assist/ui/assets/3dc6619e7e47185bacae57dfacd408ca0dcbffcaddbe0479dc7effc4800e5a41/com.splunk.assist.ui-assets
2024-02-06 04:00:55,777 INFO [assist::uiassets_modular_input.py] [download] [run] [3987] Download command complete, return_code=0
2024-02-06 04:00:55,777 INFO [assist::uiassets_modular_input.py] [config] [_set_app_config] [3987] Updating local node config, key=assets_root, value=/opt/splunk/var/splunk_assist/ui/assets/3dc6619e7e47185bacae57dfacd408ca0dcbffcaddbe0479dc7effc4800e5a41/com.splunk.assist.ui-assets
2024-02-06 04:00:55,824 INFO [assist::uiassets_modular_input.py] [config] [_set_app_config] [3987] Updating local node config, key=etag, value="8caf8e0826646505d41e4ce77ea9b72b"
2024-02-06 05:31:11,055 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_assist_enabled] [8760] Telemetry sud optin query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089/services/properties/telemetry/general/sendSupportUsage: [Errno 111] Connection refused',)
2024-02-06 05:31:11,064 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_search_head] [8760] Search head query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089//services/server/roles: [Errno 111] Connection refused',)
2024-02-06 07:31:42,413 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_assist_enabled] [13082] Telemetry sud optin query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089/services/properties/telemetry/general/sendSupportUsage: [Errno 111] Connection refused',)
2024-02-06 07:31:42,418 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_search_head] [13082] Search head query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089//services/server/roles: [Errno 111] Connection refused',)
2024-02-06 15:26:25,649 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_assist_enabled] [26553] Telemetry sud optin query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089/services/properties/telemetry/general/sendSupportUsage: [Errno 111] Connection refused',)
2024-02-06 15:26:25,676 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_search_head] [26553] Search head query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089//services/server/roles: [Errno 111] Connection refused',)
2024-02-06 20:16:48,682 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_assist_enabled] [24044] Telemetry sud optin query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089/services/properties/telemetry/general/sendSupportUsage: [Errno 111] Connection refused',)
2024-02-06 20:16:48,699 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_search_head] [24044] Search head query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089//services/server/roles: [Errno 111] Connection refused',)
2024-02-06 20:20:09,289 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_assist_enabled] [29550] Telemetry sud optin query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089/services/properties/telemetry/general/sendSupportUsage: [Errno 111] Connection refused',)
2024-02-06 20:20:09,308 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_search_head] [29550] Search head query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089//services/server/roles: [Errno 111] Connection refused',)
